In [ ]:
# Q1. What is the difference between Ordinal Encoding and Label Encoding? Provide an example of when you
# might choose one over the other.

# Ans.

# In ordinal encoding values are assigned based on the given order of category
# In Label encoding values are assigned based on the alphabetical order of category

In [ ]:
# Q2. Explain how Target Guided Ordinal Encoding works and provide an example of when you might use it in
# a machine learning project.

# Ans.

# arget Guided Ordinal Encoding is a technique used to encode categorical variables based on their relationship with the target variable in a supervised machine learning project. 
# It aims to capture the ordinal relationship between the categories and the target variable by assigning ordinal numerical values to the categories.

In [ ]:
# Q3. Define covariance and explain why it is important in statistical analysis. How is covariance calculated?

# Ans.


# Covariance is a statistical measure that quantifies the relationship and dependency between two variables. 
# It measures how changes in one variable correspond to changes in another variable. 
# Covariance provides insight into the direction (positive or negative) and strength of the relationship between variables.

In [8]:
# Q4. For a dataset with the following categorical variables: Color (red, green, blue), Size (small, medium,
# large), and Material (wood, metal, plastic), perform label encoding using Python's scikit-learn library.
# Show your code and explain the output.

# Ans.

import pandas as pd

d1 = {
    'color':['red', 'green', 'blue'],
    'size':['small', 'medium','large'],
    'material':['wood', 'metal', 'plastic']
}

df = pd.DataFrame(d1)

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

# Here we are doing encoding based on the color

color_encoded_df = pd.DataFrame(encoder.fit_transform(df['color']),columns=['color_encode'])
size_encoded_df = pd.DataFrame(encoder.fit_transform(df['size']),columns=['size_encode'])
material_encoded_df = pd.DataFrame(encoder.fit_transform(df['material']),columns=['material_encode'])

final_df = pd.concat([df,color_encoded_df,size_encoded_df,material_encoded_df],axis=1)
final_df

color    size material  color_encode  size_encode  material_encode
0    red   small     wood             2            2                2
1  green  medium    metal             1            1                0
2   blue   large  plastic             0            0                1

In [9]:
# Q5. Calculate the covariance matrix for the following variables in a dataset: Age, Income, and Education
# level. Interpret the results.

# Ans.

import numpy as np

age = [25, 30, 35, 40, 45]
income = [50000, 60000, 70000, 80000, 90000]
education = [12, 14, 16, 18, 20]

data = np.array([age, income, education])

covariance_matrix = np.cov(data)

covariance_matrix

array([[6.25e+01, 1.25e+05, 2.50e+01],
       [1.25e+05, 2.50e+08, 5.00e+04],
       [2.50e+01, 5.00e+04, 1.00e+01]])

In [ ]:
# Q6. You are working on a machine learning project with a dataset containing several categorical
# variables, including "Gender" (Male/Female), "Education Level" (High School/Bachelor's/Master's/PhD),
# and "Employment Status" (Unemployed/Part-Time/Full-Time). Which encoding method would you use for
# each variable, and why?

# Ans.

# Here we can perform OHE on Gender and Employement status , because it is not ordered data
# and Education level is ordered data , so we can use ordinal encoding

In [10]:
# Q7. You are analyzing a dataset with two continuous variables, "Temperature" and "Humidity", and two
# categorical variables, "Weather Condition" (Sunny/Cloudy/Rainy) and "Wind Direction" (North/South/
# East/West). Calculate the covariance between each pair of variables and interpret the results.

# Ans.

import numpy as np
from sklearn.preprocessing import LabelEncoder

temperature = np.array([20, 25, 18, 22, 26])
humidity = np.array([60, 70, 55, 65, 75])
weather_condition = np.array(['Sunny', 'Cloudy', 'Rainy', 'Sunny', 'Rainy'])
wind_direction = np.array(['North', 'South', 'East', 'North', 'West'])

weather_encoder = LabelEncoder()
wind_encoder = LabelEncoder()

encoded_weather = weather_encoder.fit_transform(weather_condition)
encoded_wind = wind_encoder.fit_transform(wind_direction)

data = np.column_stack((temperature, humidity, encoded_weather, encoded_wind))
covariance_matrix = np.cov(data.T)

print(covariance_matrix)

[[11.2  26.25 -1.3   3.65]
 [26.25 62.5  -2.5   8.75]
 [-1.3  -2.5   0.7  -0.35]
 [ 3.65  8.75 -0.35  1.3 ]]
